### 200 {}
GET http://localhost:5000/api/users/4

### 404
GET http://localhost:5000/api/users/100

### 201 {} 
POST http://localhost:5000/api/users
Content-Type: application/json

{
    "first_name": "Taras3",
    "last_name": "Tarasenko3",
    "email": "tt@email.test",
    "tel": "+380234569980"
}

###422

POST http://localhost:5000/api/users
Content-Type: application/json

{
    "first_name": "Taras5",
    "last_name": "Tarasenko5",
    "email": "tt1@email.test",
    "tel": "+380456567890"
}

### 422

POST http://localhost:5000/api/users
Content-Type: application/json

{
    "first_name": "Taras1",
    "last_name": "Tarasenko1",
    "email": "tt1@email.test",
    "tel": "+380234567"
}

### 200 {}
GET http://localhost:5000/api/users

###
GET http://localhost:5000/api/users?page=2&results=5

###
PATCH http://localhost:5000/api/users/1
Content-Type: application/json

{
    "first_name": "Taras5",
    "last_name": "Test",
    "email": "tt1@email.test",
    "tel": "+380456567000"
}

###
DELETE http://localhost:5000/api/users/5